---

- hosts: webservers

  sudo: yes

  vars:
    - db_name: drupal
    - db_user: drupal_user
    - db_password: drupal_db_pass

  roles:
    - update
    - php
    - mysql
    - drupal


- hosts: dbservers

  roles:
    - update
    - mysql