# roles/webserver/tasks/main.yml
---
- name: 1. install Apache
  apt: name=apache2 state=present

- name: 2. install PHP module for Apache
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - git
    - libapache2-mod-php
    - php-mcrypt
    - php-mysql
    - php-xml
    - php-gd

- name: 3. start Apache
  service: name=apache2 state=started enabled=yes

- name: 4. install Hello World PHP script
  copy: src=index.php dest=/var/www/html/index.php mode=0664

- name: Add jenkins user to groups
  user: name=jenkins groups=www-data

- name: Add Adam user to groups
  user: name=amarkosian groups=www-data

- name: Add Ninique user to groups
  user: name=nsippel groups=www-data

- name: Add Nikki user to groups
  user: name=nikkistevens groups=www-data

- name: Add Han user to groups
  user: name=hansolo groups=www-data

- name: update /var/www permissions
  file: dest=/var/www owner=root group=www-data mode=0644 recurse=yes