# roles/webserver/tasks/main.yml
---
- name: 1. install Apache
  apt: name=apache2 state=present

- name: 2. install Apache Utlities
  apt: name=apache2-utils state=present

- name: 3. install Apache Portable Runtime Utility Library - MySQL Driver 
  apt: name=libaprutil1-dbd-mysql state=present

- name: 4. install Apache Modules
  apt: name={{ item }} update_cache=yes state=present
  with_items:
    - dbd
    - authn_dbd
    - dbd_mysql

- name: 5. install PHP module for Apache
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - git
    - libapache2-mod-php
    - php-mcrypt
    - php-mysql
    - php-xml
    - php-gd

- name: 6. start Apache
  service: name=apache2 state=started enabled=yes

- name: 7. install Hello World PHP script
  copy: src=index.php dest=/var/www/html/index.php mode=0664


